server:
  port: 9099
spring:
  application:
    name: spring-cloud-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic