server:
  port: 9999
spring:
  application:
    name: eureka-consumer
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka